import type { RegistryEntry } from "../../shared.ts";

/**
 * CodeBuddy International (Tencent) — codebuddy.ai.
 *
 * Unified OpenAI-compatible gateway behind Tencent's international CodeBuddy IDE.
 * Carries 15 models (GLM, Kimi, MiniMax, DeepSeek, Hunyuan) and reasons via
 * OpenAI-style `reasoning_effort` (not vendor-native thinking shapes). Streaming
 * is forced by the executor because non-stream requests are rejected.
 */
export const codebuddy_intlProvider: RegistryEntry = {
  id: "codebuddy-intl",
  alias: "cbai",
  format: "openai",
  executor: "codebuddy-intl",
  baseUrl: "https://www.codebuddy.ai/v2/chat/completions",
  authType: "oauth",
  authHeader: "bearer",
  headers: {
    "User-Agent": "IDE/2.108.1 CodeBuddy/2.108.1",
    "X-Product": "SaaS",
    "X-IDE-Type": "IDE",
    "X-IDE-Name": "IDE",
    "x-requested-with": "XMLHttpRequest",
    "x-codebuddy-request": "1",
  },
  models: [
    {
      id: "auto",
      name: "Auto (0.79x)",
      contextLength: 1000000,
      maxOutputTokens: 48000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "fast",
      name: "Fast (0.34x)",
      contextLength: 200000,
      maxOutputTokens: 32000,
      supportsReasoning: true,
    },
    {
      id: "fast-model",
      name: "Fast Model (0.34x)",
      contextLength: 200000,
      maxOutputTokens: 32000,
      supportsReasoning: true,
    },
    {
      id: "balanced",
      name: "Balanced (0.59x)",
      contextLength: 256000,
      maxOutputTokens: 32000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "balanced-model",
      name: "Balanced Model (0.59x)",
      contextLength: 256000,
      maxOutputTokens: 32000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "primary",
      name: "Primary (3.31x)",
      contextLength: 256000,
      maxOutputTokens: 32000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "primary-model",
      name: "Primary Model (3.31x)",
      contextLength: 256000,
      maxOutputTokens: 32000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "ultimate",
      name: "Ultimate (3.33x)",
      contextLength: 512000,
      maxOutputTokens: 64000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "deep-model",
      name: "Deep Model (3.33x)",
      contextLength: 512000,
      maxOutputTokens: 64000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "hy4-preview",
      name: "Hy4 Preview (0.00x)",
      contextLength: 256000,
      maxOutputTokens: 64000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "hy3",
      name: "Hy3 (0.00x)",
      contextLength: 192000,
      maxOutputTokens: 64000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "gpt-5.6-sol",
      name: "GPT-5.6-Sol (3.47x)",
      contextLength: 256000,
      maxOutputTokens: 64000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "gpt-5.6-terra",
      name: "GPT-5.6-Terra (1.39x)",
      contextLength: 256000,
      maxOutputTokens: 64000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "gpt-5.6-luna",
      name: "GPT-5.6-Luna (0.14x)",
      contextLength: 256000,
      maxOutputTokens: 32000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "gpt-5.5",
      name: "GPT-5.5 (3.31x)",
      contextLength: 256000,
      maxOutputTokens: 64000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "gpt-5.4",
      name: "GPT-5.4 (1.65x)",
      contextLength: 256000,
      maxOutputTokens: 64000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "gpt-5.3-codex",
      name: "GPT-5.3-Codex (1.25x)",
      contextLength: 256000,
      maxOutputTokens: 64000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "gemini-3.5-flash",
      name: "Gemini-3.5-Flash (0.99x)",
      contextLength: 1000000,
      maxOutputTokens: 64000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "glm-5.3",
      name: "GLM-5.3 (0.79x)",
      contextLength: 1000000,
      maxOutputTokens: 48000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "glm-5.2",
      name: "GLM-5.2 (0.79x)",
      contextLength: 1000000,
      maxOutputTokens: 48000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "glm-5.1",
      name: "GLM-5.1",
      contextLength: 200000,
      maxOutputTokens: 48000,
      supportsReasoning: true,
    },
    {
      id: "glm-5.0",
      name: "GLM-5.0",
      contextLength: 200000,
      maxOutputTokens: 48000,
      supportsReasoning: true,
    },
    {
      id: "kimi-k3",
      name: "Kimi-K3 (1.62x)",
      contextLength: 256000,
      maxOutputTokens: 32000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "kimi-k2.6",
      name: "Kimi-K2.6 (0.52x)",
      contextLength: 256000,
      maxOutputTokens: 32000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "minimax-m3",
      name: "MiniMax-M3",
      contextLength: 512000,
      maxOutputTokens: 48000,
      supportsReasoning: true,
      supportsVision: true,
    },
    {
      id: "deepseek-v3",
      name: "DeepSeek-V3",
      contextLength: 128000,
      maxOutputTokens: 32000,
      supportsReasoning: true,
    },
  ],
};

export default codebuddy_intlProvider;
