export const NIYATNAROUTE_RESPONSE_HEADERS = {
  cache: "X-NiyatnaRoute-Cache",
  cacheHit: "X-NiyatnaRoute-Cache-Hit",
  compression: "X-NiyatnaRoute-Compression",
  costSaved: "X-NiyatnaRoute-Cost-Saved",
  decision: "X-NiyatnaRoute-Decision",
  fallbackAttempts: "X-NiyatnaRoute-Fallback-Attempts",
  latencyMs: "X-NiyatnaRoute-Latency-Ms",
  model: "X-NiyatnaRoute-Model",
  progress: "X-NiyatnaRoute-Progress",
  provider: "X-NiyatnaRoute-Provider",
  requestId: "X-NiyatnaRoute-Request-Id",
  responseCost: "X-NiyatnaRoute-Response-Cost",
  tokensIn: "X-NiyatnaRoute-Tokens-In",
  tokensOut: "X-NiyatnaRoute-Tokens-Out",
  version: "X-NiyatnaRoute-Version",
} as const;
